spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB 주소}:3306/${DB 이름}?serverTimezone=Asia/Seoul
    username: ${사용자 이름}
    password: ${사용자 비밀번호}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
OPENVIDU_URL: ${openvidu 접속 주소 이름}
OPENVIDU_SECRET: ${openvidu 비밀번호}
 
server:
  port: 5000
  ssl:
    enabled: false
    
# 파일 저장 경로 배포할 때는 리눅스에 맞춰 변경해주자
file:
  path: ${EC2 내 저장 경로}